// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsiwhxznzxeqqkjyomqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzaXdoeHpuenhlcXFranlvbXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3ODA3MzIsImV4cCI6MjA3ODM1NjczMn0.VJUun9gPPDZaYVLgLW5Bp_6wryR92DDZn3dTs2i_38k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});